//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prgm010
    {
        public string prg_no { get; set; }
        public string prg_name { get; set; }
        public string exec_file { get; set; }
        public string menu_prg { get; set; }
        public string remark { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_id { get; set; }
        public System.DateTime update_date { get; set; }
        public string log_code { get; set; }
    }
}
